#use_frameworks!

platform :ios, '8.0'

target 'NSModuleBCategory_Example' do
  pod 'NSModuleBCategory', :path => '../'
  pod 'CTMediator'
  target 'NSModuleBCategory_Tests' do
    inherit! :search_paths

    
  end
end
